siteName: Horde
homepageTitle: Agence Web Bruxelles - Performance & UX | Horde
siteUrl: https://hordeagence.com
defaultDescription: >-
  Horde, votre agence web à Bruxelles spécialisée en performance web et UX. Sites ultra-rapides,
  audit offert, optimisation SEO technique et Core Web Vitals. Collaboration directe sans intermédiaire.
locale: fr_FR
defaultOgImage: /images/og/defaultOgImage.jpg
defaultOgImageAlt: >-
  Agence web Horde Bruxelles - Conception d'interfaces web ultra-rapides et
  performantes
