siteName: Horde | Agence Web Performance & UX à Bruxelles
siteUrl: https://hordeagence.com
defaultDescription: >-
  Agence web à Bruxelles spécialisée en performance et UX. Sites ultra-rapides,
  optimisation Core Web Vitals et interfaces qui convertent. Audit gratuit.
locale: fr_FR
defaultOgImage: /images/og/defaultOgImage.jpg
defaultOgImageAlt: >-
  Agence web Horde Bruxelles - Conception d'interfaces web ultra-rapides et
  performantes
