siteName: Horde
homepageTitle: Web Agency Brussels - Performance & UX | Horde
siteUrl: https://hordeagence.com
defaultDescription: >-
  Horde, Brussels web agency focused on performance and UX. Ultra-fast websites, technical SEO
  optimization and Core Web Vitals. Free audit, direct collaboration.
locale: en_US
defaultOgImage: /images/og/defaultOgImage.jpg
defaultOgImageAlt: >-
  Horde web agency Brussels - Design of ultra-fast and high-performance web interfaces
