siteName: Horde Agence
homepageTitle: Création de site web sur mesure à Bruxelles
siteUrl: https://hordeagence.com
defaultDescription: >-
  Horde Agence, agence web à Bruxelles, crée votre site web sur mesure : design pro, site
  rapide, SEO solide et accompagnement complet. Audit site web offert.
locale: fr_FR
defaultOgImage: /images/og/defaultOgImage.jpg
defaultOgImageAlt: >-
  Horde Agence Bruxelles - Conception d'interfaces web ultra-rapides et
  performantes
