siteName: Horde
homepageTitle: Agence Web Bruxelles - Performance & UX | Horde
siteUrl: https://hordeagence.com
defaultDescription: >-
  Horde, agence web Bruxelles axée performance et UX. Sites ultra-rapides, optimisation SEO
  technique et Core Web Vitals. Audit offert, collaboration directe.
locale: fr_FR
defaultOgImage: /images/og/defaultOgImage.jpg
defaultOgImageAlt: >-
  Agence web Horde Bruxelles - Conception d'interfaces web ultra-rapides et
  performantes
